### PR TITLE
Add support for SAM E54 family MCUs

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by jepler** [comment]
Initially I wrote this so that SAMD51 and SAME54 preprocessor defines were _both_ defined for the new board.  This is tricky because when you write the `#if` blocks to do something different, you have to put the SAME54 block _first_, so I think it's not a good idea.

I'm rewriting it so that SAMx5FAM is defined for both systems, and then just one of SAMD51 or SAME54 is defined.  Thoughts @dhalbert @tannewt ?  Especially if you want to intervene on the naming, sooner is better.  This'll require additional changes in `peripherals` submodule too.

**Comment by dhalbert** [comment]
> I'm rewriting it so that SAMx5FAM is defined for both systems, and then just one of SAMD51 or SAME54 is defined. Thoughts @dhalbert @tannewt ? Especially if you want to intervene on the naming, sooner is better. This'll require additional changes in `peripherals` submodule too.

I think this makes sense, though I'm thinking of a different name. The datasheet is title "SAM D5x/E5x Family", so `SAM_D5x_E5x` or `SAMD5xE5x` makes sense to me. When I first saw `SAMx5FAM` above I was wondering what chip a `SAMD51FAM` was. If you want to include "family", I'd just spell it out as "_FAMILY` or something like that.

"D" and "E" are the only letters that Microchip uses for _x_ in " SAMx5n" right now, but someday they might add others, which might or might not be part of this family.

**Comment by dhalbert** [comment]
Are the `samd/same54/adc.c`, `clocks.c`, `dma.c`, etc., just duplicates of the `samd51` tree? If so, maybe `samd/samd51` and `samd/same54` could be combined into one tree?

**Comment by jepler** [comment]
@dhalbert I think all this is ready for review.

**Comment by dhalbert** [comment]
> Are the `samd/same54/adc.c`, `clocks.c`, `dma.c`, etc., just duplicates of the `samd51` tree? If so, maybe `samd/samd51` and `samd/same54` could be combined into one tree?

I did a meld diff of the trees, and got this:
image
The only differences are just single `#include`s, which could be conditionalized, e.g.:
image
So how do you feel about merging these into a single tree, with a bit of include conditionalization?

**Comment by jepler** [comment]
I can sure do that, if it's worth the trouble and we aren't concerned about whether it makes a (probably very hypothetical) future 'merge' from asf4 harder.

**Comment by dhalbert** [comment]
This code is not really from ASF4, it is our own invention. Since SAMD51 and SAME54 are pretty much identical, any change in this code needs to be made in two places. That is what I am worried about: the copy/pasting here is duplicated code that is going to stay identical (except for the includes). So I'd make a samd5x_e5x (or whatever combined name you're using). I know it's a bit tedious, sorry.

I don't think a merge would matter, and we have no plans to merge from updated ASF4 anyway. I did that once or twice and it was kind of horrendous.

**Review by dhalbert — APPROVED** [review]
Thank you for taking the time to generalize all this across the two chip names. Looks good!

(GitHub's idea of which files changed is pretty confusing :) )

**Pull request merged**
