### PR TITLE
fix SAMD51 pin typos: affects I2C on Grand Central

### PR DESCRIPTION
**Pull request by dhalbert**
Also fixed one touch-pin typo.

### CODE REVIEW

**Comment by dhalbert** [comment]
Will make a PR for circuitpython as soon as this is approved.

**Comment by dhalbert** [comment]
Fixes https://github.com/adafruit/circuitpython/issues/1456. I checked the whole datasheet table against the pin table.

**Review by tannewt — APPROVED** [review]
Thank you for the fix!

**Comment by Givy** [comment]
Hi,
May I inquire on what the fix is?  Are the pins 24,25 the real SDA and SCL pins on the Adafruit Metro Grand Central M4?  Thanks.

**Comment by Givy** [comment]
In their PDF file "Introducing the Adafruit Grand Central M4 Express" on page 17, it mentions the following:

SDA - the I2C (Wire) data pin. There's no pull up on this pin by default so when using with I2C, you
may need a 2.2K-10K pullup. This pin is the same as D20
SCL - the I2C (Wire) clock pin. There's no pull up on this pin by default so when using with I2C, you
may need a 2.2K-10K pullup. This pin is the same as D21

However, on the board itself there are two pins that are marked as SCL and SDA on top.  Is there a correction or different lib we should be using?

Thanks.

**Comment by ladyada** [comment]
hiya, questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)

**Comment by Givy** [comment]
Hi Ladyada,
Thanks for your kind e-mail.  I did a Google search and that's how I ended up on that web page on GitHub.  I fixed my I2C issue, but RTCZero on SAMD51 still not working and I'll get on the Forum as you suggested.

Keep up the good work.  Love the way your company encourages science and Engineering and provides access to everyone.

Thanks,
Givi

________________________________

**Pull request merged**
